### ISSUE TITLE
Don't know UUID, but need to discover & range all near by Beacons. possible?

### ISSUE THREAD

**Issue by manjunathgudisi** [Estimote/iOS-Fleet-Management-SDK#102]
Hi,
I have a requirement where I don't know the UUID of beacon(s), but I need to range all the beacons near by. Is there any API available in Estimote SDK to do this.
- manju

**Comment by Omarj** [comment]
@martinklimek but when you turn secure UUID ON I can't detect this beacon with PROXIMITY_UUID  ?
