### ISSUE TITLE
DidEnter DidExit Region on multiple beacons

### ISSUE THREAD

**Issue by mikeKane** [Estimote/iOS-Fleet-Management-SDK#116]
The solution you gave to multiple beacons helped me so much and Im stuck so I hope you can help. 

How can we determine the didexit and didenter regions per beacon? Right now I have if closestBeacon.proximity == major/minor then do this. Do I include the monitoring into that method?I'd like to have control over UILocal Notifications for entering and exiting each beacon. Well I want it to work on one beacon at the front of the store, I dont want it going off with the other two in the next room.

**Comment by danieltigse** [comment]
@mikeKane can you help me with some code to make DidEnter DidExit Region on multiple beacons work?

**Comment by mikeKane** [comment]
@danieltigse sure do you have a link to your project?

**Comment by danieltigse** [comment]
Don't worry I figure out a way to accomplish that. I just needed to initialize the CLBeaconRegion without major and minor value. Thanks.
