### ISSUE TITLE
Frequency and beaconManager:didRangeBeacons:inRegion:

### ISSUE THREAD

**Issue by macteo** [Estimote/iOS-Fleet-Management-SDK#18]
Hi there,
I've noticed that despise that the development kit iBeacons are set to emit every 200ms, the `beaconManager:didRangeBeacons:inRegion:` method is called once per second.

How can we get the update with the desired frequency?

Best regards,
Matteo

**Comment by DheerajSerachValue** [comment]
can anyone help me. My beacon is response time is too slow. It takes ateleast 30 secs to check in. is there any way to speed it up?

**Comment by heypiotr** [comment]
Can you post your questions on our forums instead:

https://forums.estimote.com

We want to keep the GitHub issue tracker for bug reports only, and it's hard to know from your short comment whether you're experiencing a bug, or just using beacon monitoring, which is known to sometimes take up to a few minutes to trigger an enter event. So let's continue this discussion on the forums.

**Comment by AshishGarud03** [comment]
startEstimoteBeaconsDiscoveryForRegion: method of ESTBeaconManager. 
@martinklimek still this method is available?
