### ISSUE TITLE
Swift example for ProximityBeacons

### ISSUE THREAD

**Issue by danieltigse** [Estimote/iOS-Fleet-Management-SDK#232]
There is a legacy example in objective-C but now it is useful to have a swift example. Thanks.
https://github.com/Estimote/iOS-SDK/blob/c0899ceab2ebd219e38e7329daef41b05d17827a/LegacyExamples/ProximityBeacons/Examples/ESTBeaconTableVC.m

**Comment by ferologics** [comment]
Hey @danieltigse ! 

Thank you for raising this issue to our awareness. We'll definitely need to update the examples soon.

Right now we're busy on other fronts but if you were successful with your implementation and care to improve this for future developers I'll be pleased to review any pull requests you submit 🙂
