### ISSUE TITLE
Utility Demo doesn't work

### ISSUE THREAD

**Issue by devstar1988** [Estimote/iOS-Fleet-Management-SDK#234]
Hi, Estimote Developers

I am trying Estimote Legacy Examples for setting my estimote beacons.
I am owner of those.

Btw, Utility Demos don't work.
Can u help me?

Regards
Jin

**Comment by ferologics** [comment]
Hey @devstar1988 ! Were you able to resolve your issue?

**Comment by devstar1988** [comment]
No, I need your help.

**Comment by ferologics** [comment]
what do you mean exactly by "setting my estimote beacons"?

**Comment by devstar1988** [comment]
I want to set my beacon’s range through my app.
So, I was interested estimote legacy sample.

There are option for changing beacon’s settings for range.
But, I can’t connect to beacon through Bluetooth.

demoViewController = [[ESTBeaconTableVC alloc] initWithScanType:ESTScanTypeBluetooth
                                                                     completion:^(ESTBluetoothBeacon *beacon) {
                                                                         
                                                                         ESTBeaconDetailsDemoVC *updateFirmwareVC = [[ESTBeaconDetailsDemoVC alloc] initWithMacAddress:beacon.identifier];
                                                                         [self.navigationController pushViewController:updateFirmwareVC animated:YES];
                                                                     }];
                break;

This code not working.

**Comment by ferologics** [comment]
Check our [SDK reference](http://estimote.github.io/iOS-SDK/) and try hacking something together, pointers

http://estimote.github.io/iOS-SDK/Classes/ESTBeaconUpdateInfo.html

I believe you should be able to update the beacon configuration using the [BeaconUpdateInfoDelegate](http://estimote.github.io/iOS-SDK/Protocols/ESBeaconUpdateInfoDelegate.html) and pass it the new [BeaconUpdateConfig](http://estimote.github.io/iOS-SDK/Classes/ESTBeaconUpdateConfig.html)
