### ISSUE TITLE
is version 4.11.0 compatible with Swift 3 ?

### ISSUE THREAD

**Issue by giluna** [Estimote/iOS-Fleet-Management-SDK#235]
Hi,

Our beacons project worked perfectly fine until we upgraded to Xcode 8 and converted our code to Swift 3.
The project is still being built successfully using EstimoteSDK Version 4.11.0 on an iOS 10 device.
The problem is that non of the events (i.e. didEnterRegion, didRangeBeacons) are being triggered anymore.

As said, it worked for us perfectly before upgrading our project from Swift 2.
Our dev beacon is still recognized in Estimote app on iOS 10 device.

Are you familiar with this problem?
Any reason what can cause it? 
Is Estimote SDK version 4.11.0 compatible with Swift 3 updates/changes?

Please advice.

Tnx.
Gil.

**Comment by NeedNap** [comment]
Hi,
we have the same issue and we need an SDK update as soon as possibile because our project does not work!!!

**Comment by giluna** [comment]
Estimote are still working on updating the documentation, the thing you can do in new SWIST 3 is to change AnyObject to Any in beacon delegates. It should the magic.
