### ISSUE TITLE
iOS 10 ESTBeaconConnection - CoreBluetooth XPC Error

### ISSUE THREAD

**Issue by gnazarkin** [Estimote/iOS-Fleet-Management-SDK#239]
Problem started with #233 on iOS 10 and that error was resolved, but now when calling `ESTBeaconConnection *connection = [ESTBeaconConnection connectionWithProximityUUID:uuid major:major minor:minor delegate:self];` it throws... `[CoreBluetooth] XPC connection invalid` and doesn't connect to beacon

**Comment by gnazarkin** [comment]
@ferologics Any updates on this? Something similar mentioned on the forums when monitoring. https://forums.estimote.com/t/swift-3-xcode-8-xpc-connection-invalid-issue/4822/9

**Comment by ferologics** [comment]
@gnazarkin did you try [acorsi's solution](https://forums.estimote.com/t/swift-3-xcode-8-xpc-connection-invalid-issue/4822/6)?

**Comment by gnazarkin** [comment]
@ferologics Yes I tried it and didn't help

**Comment by ferologics** [comment]
@gnazarkin do you have network, location and blue-tooth access enabled as well?

**Comment by gnazarkin** [comment]
@ferologics Yes

**Comment by raphaelseher** [comment]
Maybe useful from the apple developer forum.
Here the problem was caused, because CBPeripheralManager was not an instance variable
and so CoreBluetooth was not able to initialise successfully.

https://forums.developer.apple.com/thread/54510

**Comment by shattars3d** [comment]
new iOS 10.2 @gnazarkin  @ferologics 
Other improvements and fixes
Adds notification support for HomeKit accessories including window coverings, occupancy, motion, door/window, smoke, carbon monoxide, and water leak sensors
Adds notification support for HomeKit accessories when software updates are available to HomeKit accessories 
**Improves Bluetooth performance and connectivity with 3rd party accessories**

**Comment by ferologics** [comment]
@gnazarkin did iOS `10.2` update change behaviour of the error in any way? Were you successful in resolving the problem?

**Comment by gnazarkin** [comment]
@ferologics I'll give it a try as soon as I can as I still need to resolve the issue myself. Swamped with another project right now

**Comment by aj-bartocci** [comment]
I kept getting getting the "[corebluetooth] xpc connection invalid" error when trying to connect to beacons using the ESTDeviceManager with iOS 10. Connections worked fine with iOS 9 but with 10 it always timed out. I resolved the issue by adding "Privacy - Location When In Use Usage Description" permission to the plist file. @ferologics @gnazarkin

**Comment by shattars3d** [comment]
i have that in the .plist "Privacy - Location When In Use Usage Description" for iOS 10. The in app beacon **ranging** is still faulty.

**Comment by aj-bartocci** [comment]
That's strange, I have a separate app that ranges beacons and I haven't had any issues as of yet running on iOS 10. Although for that app I request the Always Usage @shattars3d

**Comment by shattars3d** [comment]
@aj-bartocci  Are you using the Estimote framework in your personal project? Or are you using the example Estimote project?

**Comment by aj-bartocci** [comment]
I'm using the framework in my own project @shattars3d
