### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by NSCabezon** [Estimote/iOS-Fleet-Management-SDK#240]
Hi! I was wondering If you could integrate carthage support :)

**Comment by beseder42** [comment]
I would also appreciate that since I don't want to commit 70MB to our repository just for the SDK.

**Comment by NSCabezon** [comment]
If you're using pods @beseder42 you shouldn't commit the Pods folder (:

**Comment by beseder42** [comment]
True for Pods! But we are using Carthage ;) So right now we would need to commit the Framework-Directory to have it on each machine on checkout. With Carthage everybody could build or download it with the same workflow.

**Comment by NSCabezon** [comment]
I guess It's not an option :(

**Comment by sebastianvarela** [comment]
yes, please!

**Comment by ferologics** [comment]
Sadly, this is **not** a priority at the moment.

Once enough people demand support we will add it to the backlog. 🔜

In meantime, promote the issue on [Product Pains](https://productpains.com/post/estimote/sdk-carthage-support) to hit the critical mass 💪😊 !

**Comment by startupthekid** [comment]
Why isn't this a priority? It should be *dead easy* to add Carthage support, just make the scheme that generates the framework "Shared". Although it might be more complicated for objective-c generated frameworks, that I'm not sure about.
