### ISSUE TITLE
com.estimote.ESTPeripheralConnector *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString substringWithRange:]: Range {0, 8} out of bounds; string length 4'

### ISSUE THREAD

**Issue by julestburt** [Estimote/iOS-Fleet-Management-SDK#253]
We are seeing this crash issue from time to time with our app. We are obviously using ESTSDK, and have got ESTLocationBeaconBulkUpdater() class instantiated - and appears to work well (mostly). I'm not sure what causes the crash though (so not sure it's BulkUpdater)

Has anyone seen or experienced this issue? We have the latest 4.14.0 release.
![screen shot 2017-04-04 at 3 16 11 pm](https://cloud.githubusercontent.com/assets/11357667/24681623/e50c53be-194a-11e7-8693-77a90192bf60.png)

Thanks, Jules.

**Comment by strazz** [comment]
Hello, I'm having a similar issue on Estimote SDK version 4.27.0. The crash (NSRangeException) happens sometimes when a beacon is discovered by ESTDeviceManager.

Thanks

exception stack trace:

Last Exception Backtrace:
0   CoreFoundation                	0x182ffed8c __exceptionPreprocess + 228
1   libobjc.A.dylib               	0x1821b85ec objc_exception_throw + 55
2   CoreFoundation                	0x182ffec6c +[NSException raise:format:] + 115
3   CoreFoundation                	0x182ee7aa8 -[__NSCFString substringWithRange:] + 167
4   POCDoubleRobotics             	0x1045b6a90 -[ESTSettingIBeaconProximityUUID parseData:] + 179
5   POCDoubleRobotics             	0x1045b639c -[ESTSettingIBeaconProximityUUID initWithData:] + 91
6   POCDoubleRobotics             	0x1046f6e14 -[ESTBeaconOperationIBeaconProximityUUID updateSettingWithData:] + 75
7   POCDoubleRobotics             	0x104710fd0 -[ESTPeripheralTypeUtility handleReadWritePacket:] + 1115
8   POCDoubleRobotics             	0x104710b54 -[ESTPeripheralTypeUtility peripheral:didUpdateValueForCharacteristic:error:] + 1027
9   CoreBluetooth                 	0x18864bc18 -[CBPeripheral handleAttributeEvent:args:attributeSelector:delegateSelector:delegateFlag:] + 239
10  CoreBluetooth                 	0x18864bd78 -[CBPeripheral handleCharacteristicEvent:characteristicSelector:delegateSelector:delegateFlag:] + 131
11  CoreBluetooth                 	0x188647714 -[CBPeripheral handleMsg:args:] + 355
12  CoreBluetooth                 	0x188642350 -[CBCentralManager handleMsg:args:] + 203
13  CoreBluetooth                 	0x188650580 __30-[CBXpcConnection _handleMsg:]_block_invoke + 59
14  libdispatch.dylib             	0x1828f0aa0 _dispatch_call_block_and_release + 23
15  libdispatch.dylib             	0x1828f0a60 _dispatch_client_callout + 15
16  libdispatch.dylib             	0x1828fa9b4 _dispatch_queue_serial_drain$VARIANT$mp + 607
17  libdispatch.dylib             	0x1828fb2fc _dispatch_queue_invoke$VARIANT$mp + 335
18  libdispatch.dylib             	0x1828fa86c _dispatch_queue_serial_drain$VARIANT$mp + 279
19  libdispatch.dylib             	0x1828fb2fc _dispatch_queue_invoke$VARIANT$mp + 335
20  libdispatch.dylib             	0x1828fbcc8 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 339
21  libdispatch.dylib             	0x182904098 _dispatch_workloop_worker_thread$VARIANT$mp + 667
22  libsystem_pthread.dylib       	0x182c23e70 _pthread_wqthread + 859
23  libsystem_pthread.dylib       	0x182c23b08 start_wqthread + 3

**Comment by chwastek** [comment]
@julestburt please fill in needed information provided when opening an issue
