### ISSUE TITLE
Header files are not copied via Cocoapods

### ISSUE THREAD

**Issue by YMonnier** [Estimote/iOS-Fleet-Management-SDK#269]
Hello,

I tried to add proximity events to my iOS app. I installed the Estimate iOS SDK via Cocoapods and following this [tutorial](http://developer.estimote.com/proximity/ios-tutorial/):

```Bash
...
Installing EstimoteSDK (5.0.0-alpha.2)
Generating Pods project
Integrating client project
Sending stats
...
```

It seems that the header files are not copied to the pod repository (see below):

<img width="301" alt="screen shot 2017-10-13 at 11 35 23 pm" src="https://user-images.githubusercontent.com/9322425/31567343-541b0cbc-b06f-11e7-82fe-aea39f37b351.png">

Some files are missing compared to your sample downloaded on your site (see below):

![screen shot 2017-10-13 at 11 38 39 pm 2](https://user-images.githubusercontent.com/9322425/31567416-b6208400-b06f-11e7-9731-a09484bb6f35.png)

You should update your pod repository.
Thanks

**Comment by airalex** [comment]
Hey @YMonnier, can you please share your Podfile? Estimote SDK 5 is still in alpha stage and `pod 'EstimoteSDK'` should result in integrating Estimote SDK 4 (the stable one that example apps use).

Estimote SDK 5's code name is Proximity SDK - it's for detecting beacons and reacting to changes in physical context of the user, this should be enough in majority of use cases for apps with beacons. Beacon settings management will be handled differently in the future. This is why you don’t see many of the classes from Estimote SDK 4 in your project with Estimote SDK 5.

For more info, check out [the blog post](http://blog.estimote.com/post/166007374930/the-most-reliable-proximity-tech-now-with-a).

**Comment by YMonnier** [comment]
Hello @airalex,

Thank you for your reply.
Below my Podfile: 

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def rx_swift
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
    pod 'RxRealmDataSources'
    pod 'RxRealm'
    
    # Networking
    pod 'Moya/RxSwift'
    pod 'Moya-ObjectMapper/RxSwift'
end

target 'PNPC-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PNPC-iOS
  rx_swift
  
  # Keyboard Manager
  pod 'IQKeyboardManagerSwift', '4.0.10'
  
  # Animations/Transitions
  pod 'Hero', '~> 0.3'

  # Firebase Cloud Messaging
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  # Estimote SDK
  pod 'EstimoteSDK', '5.0.0-alpha.2'

  target 'PNPC-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PNPC-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```
