### ISSUE TITLE
Feature Request: Add option to disable Bluetooth Settings popup with ESTDeviceManager

### ISSUE THREAD

**Issue by mhorgan1** [Estimote/iOS-Fleet-Management-SDK#279]
## Basic information

**Estimote iOS SDK version:** `4.27.0`
**iOS device(s) affected:** All models (tested on iPhone 5s and iPhone X
**iOS version(s) affected:** `iOS 11.2.6` and `iOS 11.3`

## Additional information
Please read the checklist and place `x` sign where apropriate for your use case.

* [x] My beacons have Estimote Monitoring enabled (check it in the Estimote Cloud, or via app).
* [x] My iOS device/devices supports BLE (iOS must be 5.0 or higher).
* [x] My app has `NSBluetoothPeripheralUsageDescription` in its `Info.plist` file.
* [x] My app has Location Permissions granted.
* [ ] My iOS device/devices have Bluetooth enabled.
* [x] My app has `NSLocationWhenInUseUsageDescription` and `NSLocationAlwaysAndWhenInUseUsageDescription` keys in its `Info.plist` file.
* [x] My app has `NSLocationAlwaysUsageDescription` or `NSLocationWhenInUseUsageDescription` in its `Info.plist` file.
* [ ] If my app is supporting iOS 10 and earlier, and has `NSLocationAlwaysUsageDescription` key in its `Info.plist` file.
* [x] If my app has to run in the background, it has UIBackgroundModes key with value bluetooth-central in its Info.plist file.

## Description

I'm creating an iOS app that uses Estimote beacons. It also includes _beacon telemetry_.

When I launch my app with **Bluetooth Off in Settings App**, I get a _popup on screen to go to settings to turn on bluetooth_. 

I only get this popup when I instantiate the **ESTDeviceManager** as follows. If I don't include the below lines, I don't get prompted to turn on bluetooth, but then my Telemetry won't work. 

    self.deviceManager = [ESTDeviceManager new];
    self.deviceManager.delegate = self;

Is there a way to prevent being prompted to go to settings? I have tried the following to see if it would override what's in the EstimoteSDK:

        CBCentralManager* bluetoothManager =[[CBCentralManager alloc]
                        initWithDelegate:self
                        queue:dispatch_get_main_queue() 
                        options:@{CBCentralManagerOptionShowPowerAlertKey: @(NO)}];

**Expected behavior:**

Have a way to disable the bluetooth settings popup. Get the popup if we set a flag to `true`

**Actual behavior:** 

Popup to go to settings to turn on bluetooth appears

**Comment by mhorgan1** [comment]
I have tried rolling back to [Version 4.26.3](https://github.com/Estimote/iOS-SDK/blob/master/CHANGELOG.md#4263-november-13-2017) and the bluetooth dialog no longer appears. 

Was there a flag set inside the old version of `ESTDeviceManager` that has now been changed in the newest version?

**Comment by heypiotr** [comment]
I checked and no, there was no such change. Maybe it's something else you've also done in your code?
