### ISSUE TITLE
Swift 5 / Xcode 10.2 compatibility 

### ISSUE THREAD

**Issue by dessmith** [Estimote/iOS-Fleet-Management-SDK#286]
## Swift 5 / Xcode 10.2 compatibility 

**Estimote iOS SDK version:** `4.27.0`
**iOS device(s) affected:** Building for Xcode 10.2 / Swift 5 compiler

#### Whats wrong?
When I build with Xcode 10.2 / Swift 5 compiler, I get an classic error "Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler"

#### What needs to be done?
Can this please be built with Xcode 10.2(.1) Swift 5.0, _as with ABI stability this should be the last time a maintenance update like this is required._

**Comment by heypiotr** [comment]
The Fleet Management SDK is a static Obj-C framework, so your error must be coming from another library. Maybe you meant the Proximity SDK? (https://github.com/estimote/ios-proximity-sdk) This one got the Swift 5 update in version 1.3.x.

**Comment by dessmith** [comment]
You're right, I had a moment just then. All sorted thanks
