### ISSUE TITLE
Readme should be updated

### ISSUE THREAD

**Issue by Lapinou42** [Estimote/iOS-Fleet-Management-SDK#291]
Hello :) 

Just to inform you about a small mistake. In the readme, there is:

> 3. For Swift project: you will need a bridging header, so just add a new file with Objective-C, confirm you want to a create a bridging header and just remove the not needed Objective-C file. In the bridging header, add: #import <EstimoteFleetManagement/EstimoteFleetManagement.h> For Objective-c project: add to your code #import <EstimoteFleetManagement/EstimoteFleetManagement.h>

It should be: 

> 3 For Swift project: you will need a bridging header, so just add a new file with Objective-C, confirm you want to a create a bridging header and just remove the not needed Objective-C file. In the bridging header, add: #import <EstimoteFleetManagement**SDK**/EstimoteFleetManagement**SDK**.h> For Objective-c project: add to your code #import <EstimoteFleetManagement**SDK**/EstimoteFleetManagement**SDK**.h>

EstimoteFleetManagement => EstimoteFleetManagementSDK

Thank you :)

**Comment by chwastek** [comment]
Fixed in https://github.com/Estimote/iOS-Fleet-Management-SDK/commit/867d4d83c429a80752a9de845a55a4bf107cb213 thanks for spotting this 🖖
