### ISSUE TITLE
Why would I use Estimote SDK rather than native CoreLocation?

### ISSUE THREAD

**Issue by jeffijoe** [Estimote/iOS-Fleet-Management-SDK#8]
Hi,

As far as I understand, the only difference between the Estimote SDK and the native CoreLocation + CoreBluetooth is that Estimote SDK only works with Estimote beacons.

Did I get it right? Or is there something else? Why would I use Estimote SDK instead of Core?

**Comment by mattleibow** [comment]
I know this is old, but just for reference for Xamarin platforms:
Xamarin.iOS: http://components.xamarin.com/view/estimotesdkios
Xamarin.Android: http://components.xamarin.com/view/estimotesdk
