### ISSUE TITLE
Not discovering virtual beacons (even after phone restart)

### ISSUE THREAD

**Issue by Duckbadger** [Estimote/iOS-Fleet-Management-SDK#95]
Using the example code from this repo, I cannot discover any virtual beacons from an iPad.

Scenario:
I have the example code from this repo running on iPhone 5s.
A virtual beacon is running on an iPad 4th gen using the Estimote app from the App Store.
I'm trying to discover the virtual beacon from the iPad using the iPhone 5s but nothing is being picked up.

I've looked at previous closed issues where restarting the device has fixed the issue but that hasn't worked for me, even restarting both the iPad and iPhone.

**Comment by sashakid** [comment]
Hi, has the issue with virtual beacon resolved or not? I'm trying to test indoor location in Estimote.app with fourth virtual beacon but there are only three visible beacons in indoor location setup. When I leave setup and return to beacons list - the virtual beacon is visible, but not in indoor location. Restart hasn't helped me, does anyone test indoor location with fourth virtual beacon? Thanks.

**Comment by heypiotr** [comment]
Indoor Location requires physical Estimote beacons.

(The issue originally reported in this thread was about the Examples app not detecting the virtual beacon, and that's because the virtual beacon has a different UUID.)

**Comment by sashakid** [comment]
@heypiotr Ok, I have just read it in Estimote community, thanks, sorry :-)
